name: Multi threading Load Testing

on:
  push:
    branch: [ example ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Docker build 
      run: docker build . -t ynlp
    - name: Docker run
      run: docker run --detach --name backend --publish 80:80 ynlp
    - name: testing docker
      run: docker exec backend pytest
